version: '3.8'

services:
  tasktracker:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - WEATHERAPI_KEY=${WEATHERAPI_KEY:-}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}
    volumes:
      - ./db:/app/db
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: tasktracker_network