# fly.toml app configuration file
# https://fly.io/docs/reference/configuration/

app = "tasktracker-portfolio"
primary_region = "mia"

[build]

[env]
  ENV = "production"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/"

[deploy]
  release_command = "python -c 'from backend.models import create_tables; create_tables()'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512